#!/bin/bash

#######################################################################
CHANGETO="EUCJP"
#######################################################################


. ./xnameconf

ISUTF8=`file -i aboutIf.txt | grep utf-8`
if [ -n "$ISUTF8" ]; then
  echo "UTF-8 -> $CHANGETO"
  CODE_F="UTF-8"
  CODE_T="$CHANGETO"
else
  echo "$CHANGETO -> UTF-8"
  CODE_F="$CHANGETO"
  CODE_T="UTF-8"
fi

function fileconv() {
  if [ $2 = 1 ]; then chmod 664 $1; fi
  cp $1 $1.tmp
  iconv -f ${CODE_F} -t ${CODE_T} $1.tmp > $1
  echo "  $1"
  rm $1.tmp
  if [ $2 = 1 ]; then chmod 444 $1; fi
}

function fileconv0() {
  for file; do fileconv $file 0; done
}

function fileconv1() {
  for file; do fileconv $file 1; done
}

function convArcFile() {
  if [ ! -e $1 ]; then return; fi
  echo " $1"
  chmod 664 $1
  tmpdir=tmp.$1
  mkdir $tmpdir
  cd $tmpdir
  tar xvfz ../$1 > /dev/null
  fileconv0 $2
  tar cvfz ../$1 $2 > /dev/null
  cd ..
  rm -fr $tmpdir
  chmod 444 $1
}

function convSrc() {
  fileconv0 BUILD/makefile BUILD/.lib/gcc_sample
  #fileconv1 HISTORY/*.txt
  fileconv1 ${NEWMODULE}_if.h ${NEWMODULE}_proc*.c ${NEWMODULE}_debug.*
  fileconv1 ${NEWMODULE}_extra.* ${NEWMODULE}_select.* ${NEWMODULE}_window.*
  #fileconv1 ${NEWMODULE}_signal*
  fileconv0 ${NEWMODULE}_custom.h ${NEWMODULE}_spec.*
  fileconv0 ${NEWMODULE}_test*.c main.c
}

function convArcDir() {
  if [ ! -e $1 ]; then return; fi
  echo " $1"
  chmod 664 $1
  tar xvfz $1 > /dev/null
  cd $2
  fileconv0 $3
  cd ..
  tar cvfz $1 $2 > /dev/null
  rm -fr $2
  chmod 444 $1
}

function convArcSmpl() {
  if [ ! -e $1 ]; then return; fi
  echo " $1"
  chmod 664 $1
  tar xvfz $1 > /dev/null
  cd $2
  fileconv0 $3
  spec="smpl_spec.h smpl_spec.c"
  cd spec1
  fileconv0 $spec
  cd ../spec2
  fileconv0 $spec
  cd ../..
  tar cvfz $1 $2 > /dev/null
  rm -fr $2
  chmod 444 $1
}

echo " toscom/"
fileconv1 README* *.txt xname
chmod 555 xname
fileconv0 xnameconf
convSrc
convArcFile ${NEWMODULE}_testtos.tar.gz "${NEWMODULE}_testtos.c"
convArcDir newenv.tar.gz NEWENV \
       "BUILD/makefile BUILD/.lib/gcc_sample *.c *.h newenv"
convArcDir analyzer.tar.gz analyzer \
       "BUILD/makefile anlz_* ${NEWMODULE}_spec.* ${NEWMODULE}_test.c main.c newenv"
convArcSmpl smplcomm.tar.gz smplComm \
       "BUILD/makefile BUILD/.lib/gcc_sample ${NEWMODULE}_spec.* ${NEWMODULE}_test.c smpl_if.h smpl_com.h smpl_main.c main.c newenv"

