#!/bin/bash

. ./xnameconf

function convert() {
  grep -l "${2}_" $1 | xargs sed -i.cnvbak -e "s/${2}_/${3}_/g"
  if [ "x$1" = "xREADME.md" ]; then return; fi
  grep -l "${2^^}_" $1 | xargs sed -i.cnvbak -e "s/${2^^}_/${3^^}_/g"
  if [ "x$4" = "x1" ]; then
    # 日本語を含むモジュール名だと失敗するかも
    grep -l "${2}モジュール" $1 | \
        xargs sed -i.cnvbak -e "s/${2}モジュール/${3}モジュール/g"
  fi
}

function procFiles() {
  echo ">> convert document files"
  convert "*.txt" $1 $2 1
  convert "README.md" $1 $2 1

  echo ">> convert C source files"
  convert "*.c" $1 $2 1
  echo ">> convert C header files"
  convert "*.h" $1 $2 1
  echo ">> convert BUILD/makefile"
  convert BUILD/makefile $1 $2 0
  sed -i.cnvbak -e "s/${1}\.o/${2}\.o/g" BUILD/makefile

  echo ">> rename $1 files"
  for FILE in $(ls ${1}_*.?); do mv $FILE ${FILE//${1}_/${2}_}; done

  echo ">> remove temporary files"
  rm -fr *.cnvbak BUILD/*.cnvbak
}

arctmp=".tmpArca3527"

function procArchive() {
  if [ ! -e "$1" ]; then return 0; fi
  NEWTAZ=$2
  echo ">> convert $1"
  if [ -z "$NEWTAZ" ]; then NEWTAZ=$1; fi
  mkdir $arctmp
  cd $arctmp
  mv ../$1 .
  tar xvfz $1 >& /dev/null
  rm -fr $1
  procFiles $OLDMODULE $NEWMODULE >& /dev/null
  tar cvfz $NEWTAZ * >& /dev/null
  mv $NEWTAZ ..
  cd ..
  rm -fr $arctmp
}


procFiles $OLDMODULE $NEWMODULE
procArchive ${OLDMODULE}_testtos.tar.gz ${NEWMODULE}_testtos.tar.gz

procArchive smpl_spec1.tar.gz
procArchive smpl_spec2.tar.gz

