#!/bin/bash

. ./xnameconf

function convert() {
  grep -l "${2}_" $1 | xargs sed -i.cnvbak -e "s/${2}_/${3}_/g"
  if [ "x$1" = "xREADME.md" ]; then return; fi
  grep -l "${2^^}_" $1 | xargs sed -i.cnvbak -e "s/${2^^}_/${3^^}_/g"
  if [ "x$4" = "x1" ]; then
    # 日本語を含むモジュール名だと失敗するかも
    grep -l "${2}モジュール" $1 | \
        xargs sed -i.cnvbak -e "s/${2}モジュール/${3}モジュール/g"
  fi
}

function procFiles() {
  echo ">> convert document files"
  convert "*.txt" $1 $2 1
  convert "README.md" $1 $2 1

  echo ">> convert C source files"
  convert "*.c" $1 $2 1
  echo ">> convert C header files"
  convert "*.h" $1 $2 1
  echo ">> convert BUILD/makefile"
  convert BUILD/makefile $1 $2 0
  sed -i.cnvbak -e "s/${1}\.o/${2}\.o/g" BUILD/makefile

  echo ">> rename $1 files"
  for FILE in $(ls ${1}_*.?); do mv $FILE ${FILE//${1}_/${2}_}; done

  echo ">> remove temporary files"
  rm -fr *.cnvbak BUILD/*.cnvbak
}

arctmp=".tmpArca3527"

function procArchive() {
  local OLD=$1
  local NEW=$2
  local DIR=$3

  if [ ! -e "$OLD" ]; then return 0; fi
  echo ">> convert $OLD"
  mkdir $arctmp
  cd $arctmp
  mv ../$OLD .
  tar xvfz $OLD >& /dev/null
  rm -fr $OLD
  cd $DIR
  procFiles $OLDMODULE $NEWMODULE >& /dev/null
  if [ $DIR != "." ]; then cd ..; fi
  tar cvfz $NEW * >& /dev/null
  mv $NEW ..
  cd ..
  rm -fr $arctmp
}

procFiles $OLDMODULE $NEWMODULE
procArchive ${OLDMODULE}_testtos.tar.gz ${NEWMODULE}_testtos.tar.gz .
procArchive newenv.tar.gz newenv.tar.gz NEWENV

# smplCommで使われたときは個別ファイルも変換対象になる
if [ ${PWD##*/} = "smplComm" ]; then
  . ./.s.common
  cd spec1
  procFiles $OLDMODULE $NEWMODULE
  cd ../spec2
  procFiles $OLDMODULE $NEWMODULE
  cd ..
  if [ -e ${NEWMODULE}_window.c ]; then
    swapFiles spec2
  else
    swapFiles spec1
  fi
fi

