#!/bin/bash

. ../toscom/xnameconf

if [ -f ${NEWMODULE}_window.h ]; then
  echo "this is already sample2"
  exit
fi
  
TARGET=smpl_spec2.tar.gz

echo "### extract ${TARGET}"
tar xvfz ${TARGET}

function linkFile() {
  if [ ! -f $1 ]; then
    echo "link $1"
    ln -s ../toscom/$1
  fi
}

linkFile ${NEWMODULE}_window.h
linkFile ${NEWMODULE}_window.c

sed -i -e "/^#.*FLAGS.*=.*\-lncursesw/s/#//g" BUILD/makefile
echo "activate ncurses in makefile"

