#!/bin/bash

# newenv と makefile を最新に保つパッチ処理
# 元が変わったときに、アーカイブ(z)前に実施すること

rm -fr newenv.orig newenv.rej
cp ../toscom/NEWENV/newenv .
patch newenv newenv.diff

rm -fr BUILD/makefile.orig BUILD/makefile.rej
cp ../toscom/BUILD/makefile BUILD/
patch BUILD/makefile BUILD/makefile.diff

rm -fr .com_windowSpec.h

