#!/bin/bash

. ../toscom/xnameconf
. ./.s.common

if [ ! -f ${NEWMODULE}_window.h ]; then
  echo "this is already sample1"
  exit
fi

swapFiles spec1

delFile ${NEWMODULE}_window.h
delFile ${NEWMODULE}_window.c
delSpecFile ${NEWMODULE}_windowSpec.h

sed -i -E "/^[^#].*FLAGS.*=.*\-lncursesw/s/^(.*)/#&/" BUILD/makefile
echo "deactivate ncurses in makefile"

