#!/bin/bash

. ../toscom/xnameconf
. ./.s.common

if [ -f ${NEWMODULE}_window.h ]; then
  echo "this is already sample2"
  exit
fi

swapFiles spec2

linkFile ${NEWMODULE}_window.h
linkFile ${NEWMODULE}_window.c
addSpecFile ${NEWMODULE}_windowSpec.h

sed -i -e "/^#.*FLAGS.*=.*\-lncursesw/s/#//g" BUILD/makefile
echo "activate ncurses in makefile"

