#!/bin/bash

if [ ! -f com_window.h ]; then
  echo "this is already sample1"
  exit
fi

function swapFiles() {
  echo "### overwrite from $1"
  cp $1/smpl_spec.? .
}

function delFile() {
  if [ -f $1 ]; then
    echo "delete $1"
    rm $1
  fi
}

./s2
swapFiles spec1

delFile com_window.h
delFile com_window.c

sed -i -E "/^[^#].*FLAGS.*=.*\-lncursesw/s/^(.*)/#&/" BUILD/makefile
echo "deactivate ncurses in makefile"

