#!/bin/bash

if [ ! -f com_window.h ]; then
  echo "this is already sample1"
  exit
fi

function swapFiles() {
  echo "### overwrite from $1"
  cp smpl_spec.? $2
  cp $1/smpl_spec.? .
}

function delFile() {
  if [ -f $1 ]; then
    echo "delete $1"
    rm $1
  fi
}

swapFiles spec1 spec2

delFile com_window.h
delFile com_window.c

# makefileの curses関連ライブラリの記述をコメントアウト
sed -i -E "/^[^#].*FLAGS.*=.*\-lncursesw/s/^(.*)/#&/" BUILD/makefile

