#!/bin/bash

if [ -f com_window.h ]; then
  echo "this is already sample2"
  exit
fi

function swapFiles() {
  echo "### overwrite from $1"
  cp $1/smpl_spec.? .
}

function linkFile() {
  if [ ! -f $1 ]; then
    echo "link $1"
    ln -s ../toscom/$1
  fi
}

./s1
swapFiles spec2

linkFile com_window.h
linkFile com_window.c

sed -i -e "/^#.*FLAGS.*=.*\-lncursesw/s/#//g" BUILD/makefile
echo "activate ncurses in makefile"

