#!/bin/bash

. ../toscom/xnameconf

if [ ! -f ${NEWMODULE}_window.h ]; then
  echo "this is already sample1"
  exit
fi
  
TARGET=smpl_spec1.tar.gz

echo "### extract ${TARGET}"
tar xvfz ${TARGET}

function delFile() {
  if [ -f $1 ]; then
    echo "delete $1"
    rm $1
  fi
}

delFile ${NEWMODULE}_window.h
delFile ${NEWMODULE}_window.c

sed -i -E "/^[^#].*FLAGS.*=.*\-lncursesw/s/^(.*)/#&/" BUILD/makefile
echo "deactivate ncurses in makefile"

