#!/bin/bash

if [ ! -f com_window.h ]; then
  echo "this is already sample1"
  exit
fi
  
TARGET=smpl_spec1.tar.gz

echo "### extract ${TARGET}"
tar xvfz ${TARGET}

function delFile() {
  if [ -f $1 ]; then
    echo "delete $1"
    rm $1
  fi
}

delFile com_window.h
delFile com_window.c

# makefileの curses関連ライブラリの記述をコメントアウト
sed -i -E "/^[^#].*FLAGS.*=.*\-lncursesw/s/^(.*)/#&/" BUILD/makefile

