name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: "get ctags"
      run: sudo apt install exuberant-ctags
    - name: "check gcc version"
      run: gcc -v
    - name: "prepare to build"
      run: chmod 755 i
    - name: "prepare to build"
      run: ./i
    - name: "toscom make"
      run: cd toscom/BUILD; make
    - name: "toscom make checkf"
      run: cd toscom/BUILD; make checkf
    - name: "resetTxt make"
      run: cd resetTxt/BUILD; make
    - name: "resetTxt make checkf"
      run: cd resetTxt/BUILD; make checkf
    - name: "make archive files"
      run: ./z
    - name: "check archive file"
      run: ls toscom.*.tar.gz
    - name: "[test] create test directory"
      run: mkdir test
    - name: "[test] copy archive to test"
      run: cp toscom.*.tar.gz test/
    - name: "[test] extract archive"
      run: cd test; tar xvfz toscom.*.tar.gz
    - name: "[test] toscom make"
      run: cd test/toscom/BUILD; make
    - name: "[test] extract smplComm"
      run: cd test; tar xvfz toscom/smplcomm.tar.gz
    - name: "[test] smplComm ver1 make"
      run: cd test/smplComm/BUILD; make
    - name: "[test] smplComm ver1 make checkf"
      run: cd test/smplComm/BUILD; make checkf
    - name: "[test] convert to smplComm ver2"
      run: cd test/smplComm; ./s2
    - name: "[test] smplComm ver2 make"
      run: cd test/smplComm/BUILD; make init
    - name: "[test] smplComm ver2 make checkf"
      run: cd test/smplComm/BUILD; make checkf
    - name: "[test] extract anayzer"
      run: cd test; tar xvfz toscom/analyzer.tar.gz
    - name: "[test] analyzer make"
      run: cd test/analyzer/BUILD; make
    - name: "[test] analyzer make checkf"
      run: cd test/analyzer/BUILD; make checkf
    #- name: try to execute checker
    #  run: ./c

