name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: get ctags
      run: sudo apt install exuberant-ctags
    - name: check gcc version
      run: gcc -v
    - name: prepare com_test.c
      run: cp toscom/TEST/com_test.c toscom/
    - name: make
      run: cd toscom/BUILD; make
    - name: change permission e
      run: chmod 755 e
    - name: execute e to change permission of others
      run: ./e
    - name: execute smplComm/newenv
      run: cd smplComm; ./newenv
    - name: execute analyzer/newenv
      run: cd analyzer; ./newenv
    - name: make archive files
      run: ./z
